/*
-----------------------------------------------------------------------------
Filename:    KYMyStar.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/
#ifndef __KYMyStar_h_
#define __KYMyStar_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../../res/Resource.h"
#endif

class CaelumModule;
class Land;
class Forest;
class Object3D;
class Missile;
class SceneMenu;
class Radar;

namespace MyGUI{
	class Gui;
	class OgrePlatform;
}

class KYMyStar : public BaseApplication
{
public:
    KYMyStar(void);
    virtual ~KYMyStar(void);
	void moveCameraToBeginPos();
protected:
    void createScene(void);
	bool frameEnded(const Ogre::FrameEvent& evt);
	void createMyGui();
protected:
	bool keyPressed( const OIS::KeyEvent &arg );
	bool keyReleased( const OIS::KeyEvent &arg );
	bool mouseMoved( const OIS::MouseEvent &arg );
	bool mousePressed( const OIS::MouseEvent &arg, OIS::MouseButtonID id );
	bool mouseReleased( const OIS::MouseEvent &arg, OIS::MouseButtonID id );
	void loadResources(void);
private:
	CaelumModule* mCaelum;
	Land* mLand;
	Forest* mForest;

	Object3D* mBMP;
	Missile* mMissile;

	MyGUI::Gui* mGui;
	MyGUI::OgrePlatform* mOgrePlatform;

	SceneMenu* mMenu;
	Radar* mRadar;
};

#endif // #ifndef __KYMyStar_h_
